# Generated by Django 2.2.2 on 2020-12-12 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('regid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_of_join', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics', models.IntegerField(null=True)),
                ('maths', models.IntegerField(null=True)),
                ('science', models.IntegerField(null=True)),
                ('social', models.IntegerField(null=True)),
                ('english', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
