# Generated by Django 2.2.2 on 2020-12-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201212_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
